apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  namespace: {{ .Values.global.namespace }}

spec:
  selector:
    app: inventory-service

  ports:
    - port: {{ .Values.inventory.service.port }}
      targetPort: {{ .Values.inventory.service.targetPort }}

  type: {{ .Values.inventory.service.type }}
