apiVersion: v1
kind: Service

metadata:
  name: frontend-service
  namespace: {{ .Values.global.namespace }}

spec:
  selector:
    app: frontend-service

  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.targetPort }}

  type: ClusterIP