global:
  namespace: devsecops

imagePullSecrets:
  - name: ecr-registry-secret

users:
  replicas: 1

  image:
    repository: 359062857260.dkr.ecr.us-east-1.amazonaws.com/devsecops/users-service
    tag: "build-55-ef553ac"
    pullPolicy: Always

  service:
    port: 8000
    targetPort: 8000

  probes:
    readiness:
      path: /health
      initialDelaySeconds: 5
      periodSeconds: 5
      timeoutSeconds: 3
      failureThreshold: 10

    liveness:
      path: /health
      initialDelaySeconds: 15
      periodSeconds: 10
      timeoutSeconds: 3
      failureThreshold: 3

  database:
    host: users-db
    port: 5432
    secretName: users-db-secret
    secretKey: DATABASE_URL

    image:
      repository: postgres
      tag: "16"

    replicas: 1

    readiness:
      command: "pg_isready -U users -d users_db"
      initialDelaySeconds: 5
      periodSeconds: 5
      timeoutSeconds: 3
      failureThreshold: 20

    storage:
      size: 1Gi
      accessMode: ReadWriteOnce
      mountPath: /var/lib/postgresql/data

inventory:
  replicas: 1

  image:
    repository: 359062857260.dkr.ecr.us-east-1.amazonaws.com/devsecops/inventory-service
    tag: "build-55-ef553ac"
    pullPolicy: Always

  service:
    type: ClusterIP
    port: 8000
    targetPort: 8000

  probes:
    readiness:
      path: /health
      initialDelaySeconds: 5
      periodSeconds: 5
      timeoutSeconds: 3
      failureThreshold: 10

    liveness:
      path: /health
      initialDelaySeconds: 15
      periodSeconds: 10
      timeoutSeconds: 3
      failureThreshold: 3

  database:
    host: inventory-db
    port: 5432
    secretName: inventory-db-secret
    secretKey: DATABASE_URL

    image:
      repository: postgres
      tag: "16"

    replicas: 1

    readiness:
      command: "pg_isready -U inventory -d inventory_db"
      initialDelaySeconds: 5
      periodSeconds: 5
      timeoutSeconds: 3
      failureThreshold: 20

    storage:
      size: 1Gi
      accessMode: ReadWriteOnce
      mountPath: /var/lib/postgresql/data

orders:
  replicas: 1

  image:
    repository: 359062857260.dkr.ecr.us-east-1.amazonaws.com/devsecops/orders-service
    tag: "build-55-ef553ac"
    pullPolicy: Always

  service:
    type: ClusterIP
    port: 8000
    targetPort: 8000

  probes:
    readiness:
      path: /health
      initialDelaySeconds: 5
      periodSeconds: 5
      timeoutSeconds: 3
      failureThreshold: 10

    liveness:
      path: /health
      initialDelaySeconds: 15
      periodSeconds: 10
      timeoutSeconds: 3
      failureThreshold: 3

  config:
    usersUrl: "http://users-service:8000"
    inventoryUrl: "http://inventory-service:8000"
    httpTimeoutSeconds: "3"

  database:
    host: orders-db
    port: 5432
    secretName: orders-db-secret
    secretKey: DATABASE_URL

    image:
      repository: postgres
      tag: "16"

    replicas: 1

    readiness:
      command: "pg_isready -U orders -d orders_db"
      initialDelaySeconds: 5
      periodSeconds: 5
      timeoutSeconds: 3
      failureThreshold: 20

    storage:
      size: 1Gi
      accessMode: ReadWriteOnce
      mountPath: /var/lib/postgresql/data

ingress:
  enabled: true
  className: nginx

  paths:
    - path: /users
      pathType: Prefix
      serviceName: users-service
      servicePort: 8000

    - path: /items
      pathType: Prefix
      serviceName: inventory-service
      servicePort: 8000

    - path: /inventory
      pathType: Prefix
      serviceName: inventory-service
      servicePort: 8000

    - path: /orders
      pathType: Prefix
      serviceName: orders-service
      servicePort: 8000

frontend:
  replicas: 1

  image:
    repository: 359062857260.dkr.ecr.us-east-1.amazonaws.com/frontend-service
    tag: "build-55-ef553ac"
    pullPolicy: Always

  service:
    port: 80
    targetPort: 80
