apiVersion: v1
kind: Service
metadata:
  name: orders-db
  namespace: devsecops

spec:
  clusterIP: None

  selector:
    app: orders-db

  ports:
    - port: 5432
      targetPort: 5432

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: orders-db
  namespace: devsecops

spec:
  serviceName: orders-db
  replicas: 1

  selector:
    matchLabels:
      app: orders-db

  template:
    metadata:
      labels:
        app: orders-db

    spec:
      containers:
        - name: postgres
          image: postgres:16

          ports:
            - containerPort: 5432

          envFrom:
            - secretRef:
                name: orders-db-secret

          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - pg_isready -U orders -d orders_db
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 20

          volumeMounts:
            - name: orders-db-storage
              mountPath: /var/lib/postgresql/data

  volumeClaimTemplates:
    - metadata:
        name: orders-db-storage

      spec:
        accessModes:
          - ReadWriteOnce

        resources:
          requests:
            storage: 1Gi