apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - ingress.yaml

  - users/db.yaml
  - users/deployment.yaml
  - users/service.yaml

  - inventory/db.yaml
  - inventory/deployment.yaml
  - inventory/service.yaml

  - orders/db.yaml
  - orders/configmap.yaml
  - orders/deployment.yaml
  - orders/service.yaml